---

# doesnt work for whatever reason
# - name: Create temporary build directory for ffmpeg and motion build
#   tempfile:
#     state: directory
#     suffix: build
#   register: tmp_dir

- name: Copy install scripts ffmpeg and motion
  copy:
    src: "{{ item }}"
    dest: "{{ build_folder }}"
    mode: 0777
  loop:
    - ffmpeg_build.sh
    - motion_build.sh
    - RTSP_lower_transport_TCP.patch
    - time_t.patch
  tags:
    - build

- name: Build ffmpeg
  shell: "{{ build_folder }}/ffmpeg_build.sh"
  tags:
    - build

- name: Install ffmpeg library
  shell: |
    cd "{{ build_folder }}/FFmpeg"
    make install
    ldconfig
  become: true
  tags:
    - install

- name: Build motion
  shell: "{{ build_folder }}/motion_build.sh"
  tags:
    - build

- name: Install motion
  shell: |
    cd "{{ build_folder }}/{{ motion_build_folder }}"
    cp src/motion  /usr/local/bin/motiond
    chmod 777 /usr/local/bin/motiond
  become: true
  tags:
    - install

- name: Install motion_helper.py
  template:
    src: usr/bin/motion_helper.py
    dest: /usr/bin/motion_helper.py
    owner: andre
    group: andre
    mode: 777
  become: true
  ignore_errors: yes
  tags:
    - install

- name: Install motion *.conf and mask files
  template:
    src: "usr/local/etc/motion/{{ item }}"
    dest: /usr/local/etc/motion/
    owner: andre
    group: andre
    mode: 0640
  loop:
    - motion.conf    
    - front_left.conf
    - front_up.conf
    - left_aisle.conf
    - right_aisle.conf
    - broken_static.conf
    - mask_camera_low.pgm
    - mask_camera_street.pgm
  become: true
  tags:
    - config
    - install
    - motion